spring.application.name=quantity-measurement-app

# ===============================
# ? RENDER PORT FIX
# ===============================
server.port=${PORT:8080}

# ===============================
# ? H2 DATABASE (TEMP)
# ===============================
spring.datasource.url=jdbc:h2:mem:quantitymeasurementdb;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ===============================
# ? JPA / HIBERNATE
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# IMPORTANT
spring.jpa.defer-datasource-initialization=true

# ===============================
# ? H2 CONSOLE
# ===============================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# ===============================
# ? SWAGGER
# ===============================
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# ===============================
# ?? ACTUATOR
# ===============================
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# ===============================
# ? LOGGING
# ===============================
logging.level.com.app.quantitymeasurement=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG